---

language: python
sudo: required

services:
  - docker

env:
  - OS_VERSION=7
  - OS_VERSION=6

before_install:
  - sudo docker pull centos:${OS_VERSION}

install:
  # Run the container in detached mode. The sleep 300 will keep the container running for 300 seconds before it is killed.
  - sudo docker run --detach --volume="${PWD}":/etc/ansible/roles/ansible-java-8:ro --name centos-${OS_VERSION} centos:${OS_VERSION} sleep 300
  # Install the EPEL packages
  - sudo docker exec centos-${OS_VERSION} yum -y install epel-release
  # Install the Ansible packages
  - sudo docker exec centos-${OS_VERSION} yum -y install ansible

script:
  # Check syntax of Ansible role
  - sudo docker exec centos-${OS_VERSION} ansible-playbook /etc/ansible/roles/ansible-java-8/tests/test.yaml --syntax-check
  # Run Ansible role
  - sudo docker exec centos-${OS_VERSION} ansible-playbook /etc/ansible/roles/ansible-java-8/tests/test.yaml
  # Check that the Java version is 8
  - sudo docker exec centos-${OS_VERSION} java -version 2>&1 | awk -F\" '/version/ {print $2}' | grep "1.8.0" && (echo "Version test: pass" && exit 0) || (echo "Version test: fail" && exit 1)
  # Check Java executable location, references java alternatives
  - sudo docker exec centos-${OS_VERSION} whereis java 2>&1 | awk -F\" '/java:/ {print $1}' | grep "\/usr\/bin\/java" && (echo "Executable location test (/usr/bin/java): pass"  && exit 0) || (echo "Executable location test (/usr/bin/java): fail" && exit 1)

after_script:
  - sudo docker stop centos-${OS_VERSION}

notifications:
  email:
    - giveit@gmail.com
